import 'package:fifagen/models/user.dart';
import 'package:fifagen/notifiers/auth_api.dart';
import 'package:fifagen/notifiers/users_api.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

/// Used to create user-dependant objects that need to be accessible by all widgets.
/// This widget should live above the [MaterialApp].
/// See [AuthWidget], a descendant widget that consumes the user generated by this builder.
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder({Key key, @required this.builder}) : super(key: key);
  final Widget Function(BuildContext, User) builder;

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthNotifier>(context);
    final _user = authService.user;
    if (_user != null) {
      MultiProvider(
        providers: [
          ChangeNotifierProvider(
            create: (_) => UsersNotifier(_user.id),
          ),
        ],
        child: builder(context, _user),
      );
    }
    return builder(context, _user);
  }
}
